version: '3.8'

services:
  # API Service
  api:
    profiles: ["prod"]
    image: ${API_IMAGE:-netmind-workflow:latest}
    container_name: netmind-workflow-api
    environment:
      - PYTHONPATH=/app/src
      - LOG_LEVEL=INFO
    networks:
      - netmind-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "${API_PORT:-8000}:8000"

  # API Service for development (hot reload, bind mounts)
  api-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: netmind-workflow-api-dev
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app/src
      - LOG_LEVEL=DEBUG
      - ENV=development
    ports:
      - "${API_PORT:-8000}:8000"
      
  redis:
    image: redis:7-alpine
    container_name: netmind-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - netmind-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  netmind-network:
    driver: bridge
    name: netmind-network

volumes:
  redis_data:
    name: netmind-redis-data
