version: '3.8'

# Development overrides for docker-compose.yml
services:
  netmind-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app/src
      - DAGSTER_HOME=/app/.dagster
      - LOG_LEVEL=DEBUG
      - ENV=development
    command: python -c "print('Development container ready'); import time; time.sleep(3600)"

  dagster-webserver:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app/src
      - DAGSTER_HOME=/app/.dagster
      - LOG_LEVEL=DEBUG
      - ENV=development

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app/src
      - DAGSTER_HOME=/app/.dagster
      - LOG_LEVEL=DEBUG
      - ENV=development

  postgres-db:
    environment:
      - POSTGRES_DB=dagster_dev
      - POSTGRES_USER=dagster_dev
      - POSTGRES_PASSWORD=dagster_dev_password
