---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	http_user_infor(http_user_infor)
	http_fc_scope_example(http_fc_scope_example)
	http_ds_scope_example(http_ds_scope_example)
	code_workers_desc(code_workers_desc)
	CLS_SCOPE_AGENT(CLS_SCOPE_AGENT)
	CLS_QUERY_TYPE_AGENT(CLS_QUERY_TYPE_AGENT)
	CLS_WORKER_AGENT(CLS_WORKER_AGENT)
	PLANNER_AGENT(PLANNER_AGENT)
	RESEARCHER_AGENT(RESEARCHER_AGENT)
	MASTER_AGENT(MASTER_AGENT)
	FUNCTION_CALLER_AGENT(FUNCTION_CALLER_AGENT)
	DOCS_SEARCHER_AGENT(DOCS_SEARCHER_AGENT)
	WEBS_SEARCHER_AGENT(WEBS_SEARCHER_AGENT)
	NETMIND_INFOR_AGENT(NETMIND_INFOR_AGENT)
	REGION_IDENTIFIER_AGENT(REGION_IDENTIFIER_AGENT)
	TIME_IDENTIFIER_AGENT(TIME_IDENTIFIER_AGENT)
	EMPLOYEE_INFOR_AGENT(EMPLOYEE_INFOR_AGENT)
	CALCULATOR_AGENT(CALCULATOR_AGENT)
	AGENTX_AGENT(AGENTX_AGENT)
	SYNTHESIZER_AGENT(SYNTHESIZER_AGENT)
	SUMMARIZER_AGENT(SUMMARIZER_AGENT)
	__end__([<p>__end__</p>]):::last
	AGENTX_AGENT -.-> MASTER_AGENT;
	AGENTX_AGENT -.-> RESEARCHER_AGENT;
	AGENTX_AGENT -.-> SUMMARIZER_AGENT;
	AGENTX_AGENT -.-> SYNTHESIZER_AGENT;
	AGENTX_AGENT -.-> __end__;
	CALCULATOR_AGENT -.-> MASTER_AGENT;
	CALCULATOR_AGENT -.-> RESEARCHER_AGENT;
	CALCULATOR_AGENT -.-> __end__;
	CLS_QUERY_TYPE_AGENT -.-> CLS_WORKER_AGENT;
	CLS_QUERY_TYPE_AGENT -.-> PLANNER_AGENT;
	CLS_SCOPE_AGENT -.-> CLS_QUERY_TYPE_AGENT;
	CLS_SCOPE_AGENT -.-> MASTER_AGENT;
	CLS_WORKER_AGENT -.-> DOCS_SEARCHER_AGENT;
	CLS_WORKER_AGENT -.-> FUNCTION_CALLER_AGENT;
	CLS_WORKER_AGENT -.-> NETMIND_INFOR_AGENT;
	CLS_WORKER_AGENT -.-> REGION_IDENTIFIER_AGENT;
	CLS_WORKER_AGENT -.-> TIME_IDENTIFIER_AGENT;
	CLS_WORKER_AGENT -.-> WEBS_SEARCHER_AGENT;
	EMPLOYEE_INFOR_AGENT -.-> MASTER_AGENT;
	EMPLOYEE_INFOR_AGENT -.-> RESEARCHER_AGENT;
	EMPLOYEE_INFOR_AGENT -.-> __end__;
	FUNCTION_CALLER_AGENT -.-> AGENTX_AGENT;
	FUNCTION_CALLER_AGENT -.-> MASTER_AGENT;
	FUNCTION_CALLER_AGENT -.-> RESEARCHER_AGENT;
	FUNCTION_CALLER_AGENT -.-> SUMMARIZER_AGENT;
	FUNCTION_CALLER_AGENT -.-> SYNTHESIZER_AGENT;
	FUNCTION_CALLER_AGENT -.-> __end__;
	MASTER_AGENT -.-> DOCS_SEARCHER_AGENT;
	MASTER_AGENT -.-> EMPLOYEE_INFOR_AGENT;
	MASTER_AGENT -.-> FUNCTION_CALLER_AGENT;
	MASTER_AGENT -.-> NETMIND_INFOR_AGENT;
	MASTER_AGENT -.-> REGION_IDENTIFIER_AGENT;
	MASTER_AGENT -.-> TIME_IDENTIFIER_AGENT;
	MASTER_AGENT -.-> WEBS_SEARCHER_AGENT;
	MASTER_AGENT -.-> __end__;
	NETMIND_INFOR_AGENT -.-> MASTER_AGENT;
	NETMIND_INFOR_AGENT -.-> RESEARCHER_AGENT;
	NETMIND_INFOR_AGENT -.-> __end__;
	PLANNER_AGENT --> RESEARCHER_AGENT;
	REGION_IDENTIFIER_AGENT -.-> MASTER_AGENT;
	REGION_IDENTIFIER_AGENT -.-> RESEARCHER_AGENT;
	REGION_IDENTIFIER_AGENT -.-> __end__;
	RESEARCHER_AGENT -.-> CALCULATOR_AGENT;
	RESEARCHER_AGENT -.-> DOCS_SEARCHER_AGENT;
	RESEARCHER_AGENT -.-> FUNCTION_CALLER_AGENT;
	RESEARCHER_AGENT -.-> SUMMARIZER_AGENT;
	RESEARCHER_AGENT -.-> SYNTHESIZER_AGENT;
	RESEARCHER_AGENT -.-> WEBS_SEARCHER_AGENT;
	RESEARCHER_AGENT -.-> __end__;
	TIME_IDENTIFIER_AGENT -.-> MASTER_AGENT;
	TIME_IDENTIFIER_AGENT -.-> RESEARCHER_AGENT;
	TIME_IDENTIFIER_AGENT -.-> __end__;
	WEBS_SEARCHER_AGENT -.-> MASTER_AGENT;
	WEBS_SEARCHER_AGENT -.-> RESEARCHER_AGENT;
	WEBS_SEARCHER_AGENT -.-> __end__;
	__start__ --> http_ds_scope_example;
	__start__ --> http_fc_scope_example;
	__start__ --> http_user_infor;
	code_workers_desc --> CLS_SCOPE_AGENT;
	http_ds_scope_example --> code_workers_desc;
	http_fc_scope_example --> code_workers_desc;
	http_user_infor --> code_workers_desc;
	DOCS_SEARCHER_AGENT --> __end__;
	SUMMARIZER_AGENT --> __end__;
	SYNTHESIZER_AGENT --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
