workers:
  - "FUNCTION_CALLER_AGENT"
  - "DOCS_SEARCHER_AGENT"
  - "NETMIND_INFOR_AGENT"
  - "REGION_IDENTIFIER_AGENT"
  - "WEBS_SEARCHER_AGENT"
  - "TIME_IDENTIFIER_AGENT"
  - "EMPLOYEE_INFOR_AGENT"
  - "REMINDER_AGENT"